In [50]:
import torch
import numpy as np

### Tensors

Initialization:

In [51]:
# From list

data = [[1,2,3], [4,5,6]]
x_data = torch.tensor(data)

print(x_data)

# From numpy

np_data = np.array(data)
x_np = torch.from_numpy(np_data)

print(x_np)

# From tensor

x_ones = torch.ones_like(x_data)
print(x_ones)

x_rand = torch.rand_like(x_data, dtype=torch.float)
print(x_rand)


tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1, 1, 1],
        [1, 1, 1]])
tensor([[0.3816, 0.1257, 0.5065],
        [0.4432, 0.4455, 0.1324]])


Define from `shape`:

In [52]:
shape = (2,3)

ones_tensor = torch.ones(shape)
print(ones_tensor)

rand_tensor = torch.rand(shape)
print(rand_tensor)

zeros_tensor = torch.zeros(shape)
print(zeros_tensor)

# ------------------------------------

shape_3D = (2,2,3)

ones_tensor_3D = torch.ones(shape_3D)
print(ones_tensor_3D)

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0.9837, 0.0264, 0.8687],
        [0.1093, 0.8314, 0.4055]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]])


Attributes of a tensor:

In [53]:
my_tensor = torch.rand(3,4)

print(my_tensor.shape)
print(my_tensor.dtype)
print(my_tensor.device)


torch.Size([3, 4])
torch.float32
cpu


### Device

Move tensors to GPU:

In [54]:
if torch.accelerator.is_available():
    my_tensor = my_tensor.to(torch.accelerator.current_accelerator())

my_tensor.device

device(type='cuda', index=0)

### Basic operations

Indexing and slicing are similar to NumPy API:

In [55]:
print('First row: ', my_tensor[0])
print('First column: ', my_tensor[:, 0])
print('First column: ', my_tensor[..., 0])
print('Last column: ', my_tensor[:, -1])
print('Last column: ', my_tensor[..., -1])

my_tensor

First row:  tensor([0.3744, 0.0514, 0.2590, 0.4637], device='cuda:0')
First column:  tensor([0.3744, 0.7156, 0.9341], device='cuda:0')
First column:  tensor([0.3744, 0.7156, 0.9341], device='cuda:0')
Last column:  tensor([0.4637, 0.3124, 0.6661], device='cuda:0')
Last column:  tensor([0.4637, 0.3124, 0.6661], device='cuda:0')


tensor([[0.3744, 0.0514, 0.2590, 0.4637],
        [0.7156, 0.9893, 0.3032, 0.3124],
        [0.9341, 0.4510, 0.2527, 0.6661]], device='cuda:0')

Concatenation:

In [56]:
t0 = torch.zeros(2,3).to(torch.accelerator.current_accelerator())
t1 = torch.ones(2,3).to(torch.accelerator.current_accelerator())
t2 = torch.rand(2,3).to(torch.accelerator.current_accelerator())

t3 = torch.cat([t0, t1, t2], dim=0)
print(t3)

t4 = torch.cat([t0, t1, t2], dim=1)
print(t4)

tensor([[0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000],
        [1.0000, 1.0000, 1.0000],
        [1.0000, 1.0000, 1.0000],
        [0.3783, 0.9479, 0.2598],
        [0.4806, 0.8983, 0.4893]], device='cuda:0')
tensor([[0.0000, 0.0000, 0.0000, 1.0000, 1.0000, 1.0000, 0.3783, 0.9479, 0.2598],
        [0.0000, 0.0000, 0.0000, 1.0000, 1.0000, 1.0000, 0.4806, 0.8983, 0.4893]],
       device='cuda:0')


Flatten:

In [57]:
t3.flatten()

tensor([0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 1.0000, 1.0000, 1.0000,
        1.0000, 1.0000, 1.0000, 0.3783, 0.9479, 0.2598, 0.4806, 0.8983, 0.4893],
       device='cuda:0')

### Arithmetic operations

In [58]:
tensor = torch.rand(2,3)

print(tensor)

# Transpose
print(tensor.T)

# Matrix multiplication
y1 = tensor @ tensor.T
print(y1)

y2 = tensor.matmul(tensor.T)
print(y2)

y3 = torch.rand_like(y1)
torch.matmul(tensor, tensor.T, out=y3)
print(y3)

# Element-wise product
z1 = tensor * tensor
print(z1)

z2 = tensor.mul(tensor)
print(z2)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)
print(z3)

tensor([[0.5754, 0.6442, 0.3536],
        [0.3857, 0.3299, 0.1886]])
tensor([[0.5754, 0.3857],
        [0.6442, 0.3299],
        [0.3536, 0.1886]])
tensor([[0.8711, 0.5012],
        [0.5012, 0.2932]])
tensor([[0.8711, 0.5012],
        [0.5012, 0.2932]])
tensor([[0.8711, 0.5012],
        [0.5012, 0.2932]])
tensor([[0.3311, 0.4150, 0.1250],
        [0.1488, 0.1088, 0.0356]])
tensor([[0.3311, 0.4150, 0.1250],
        [0.1488, 0.1088, 0.0356]])
tensor([[0.3311, 0.4150, 0.1250],
        [0.1488, 0.1088, 0.0356]])


Single-element tensors and how to convert them to numerical values:

In [59]:
tensor = torch.ones(2,3)

agg = tensor.sum()
print(type(agg))

agg_item = agg.item()
print(type(agg_item))

<class 'torch.Tensor'>
<class 'float'>


In-place operations (denoted by suffix `_`). Their use is discouraged:

In [60]:
print(tensor)
tensor.add_(5)
print(tensor)

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[6., 6., 6.],
        [6., 6., 6.]])


### Bridge with NumPy

Tensor to NumPy array:

In [62]:
t = torch.ones(5)
print(t)

n = t.numpy()
print(n)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]



A change in the tensor reflects in the NumPy array:


In [ ]:
t.add_(1)
print(t)
print(n)

NumPy array to Tensor:

In [66]:
n = np.ones(5)
t = torch.from_numpy(n)

np.add(n, 1, out=n)
print(t)
print(n)

tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
[2. 2. 2. 2. 2.]
